// resources/js/components/potluck/board.vue
<template>
	<div class="responsive">
		<div class="mainSquare">

			<div class="row top">
				<div class="square2" id="20"><span class="corner corner1">free <br /> parking</span></div>
				<div class="square1" id="21">
					<div class="header header-top red"></div>
					<div class="firstLine firstLine-top rotation2">kentucky <br /> avenue</div>
				</div>
				<div class="square1" id="22">					
					<div class="firstLine firstLine-top no-color rotation2">chance</div>
				</div>
				<div class="square1" id="23">
					<div class="header header-top red"></div>
					<div class="firstLine firstLine-top rotation2">indiana <br /> avenue</div>
				</div>
				<div class="square1" id="24">
					<div class="header header-top red"></div>
					<div class="firstLine firstLine-top rotation2">illinios <br /> avenue</div>
				</div>
				<div class="square1" id="25">
					<div class="firstLine firstLine-top no-color rotation2">b. & o. <br /> railroad</div>
				</div>
				<div class="square1" id="26">
					<div class="header header-top yellow"></div>
					<div class="firstLine firstLine-top rotation2">atlantic <br /> avenue</div>
				</div>
				<div class="square1" id="27">
					<div class="header header-top yellow"></div>
					<div class="firstLine firstLine-top rotation2">ventnor <br /> avenue</div>
				</div>
				<div class="square1" id="28">					
					<div class="firstLine firstLine-top no-color rotation2">water <br /> works</div>
				</div>
				<div class="square1" id="29">
					<div class="header header-top yellow"></div>
					<div class="firstLine firstLine-top rotation2">marvin <br /> gardens</div>
				</div>
				<div class="square2" id="30"><span class="corner corner2">go to<br />jail</span></div>
			</div>
			
			<div class="row center">
				<div class="square2">
					<div class="squareSide" id="19">
						<div class="headerSide header-left orange"></div>
						<div class="firstLine firstLine-left rotation1">new york <br /> avenue</div>
					</div>
					<div class="squareSide" id="18">
						<div class="headerSide header-left orange"></div>
						<div class="firstLine firstLine-left rotation1">tennessee <br /> avenue</div>
					</div>
					<div class="squareSide" id="17">						
						<div class="firstLine firstLine-left no-color rotation1">community<br /> chest</div>
					</div>
					<div class="squareSide" id="16">
						<div class="headerSide header-left orange"></div>
						<div class="firstLine firstLine-left rotation1">st.james <br />place</div>
					</div>
					<div class="squareSide" id="15">						
						<div class="firstLine firstLine-left no-color rotation1">pennsylvania<br> railroad</div>
					</div>
					<div class="squareSide" id="14">
						<div class="headerSide header-left purple"></div>
						<div class="firstLine firstLine-left rotation1">virginia<br /> avenue</div>
					</div>
					<div class="squareSide" id="13">
						<div class="headerSide header-left purple"></div>
						<div class="firstLine firstLine-left rotation1">states<br /> avenue</div>
					</div>
					<div class="squareSide" id="12">						
						<div class="firstLine firstLine-left no-color rotation1">electric<br />company</div>
					</div>
					<div class="squareSide" id="11">
						<div class="headerSide header-left white"></div>
						<div class="firstLine firstLine-left rotation1">columbian<br />chiba</div>
					</div>
				</div>
				<div class="square9">
					<div class="card-box card-blue">
						<div class="card-blue-inside"></div>
					</div>
					<div class="logoBox">
						<span class="logoName">Pot Luck</span>
					</div>
					<div class="card-box card-orange">
						<div class="card-orange-inside"></div>						
					</div>
				</div>
				<div class="square2">
					<div class="squareSide" id="31">
						<div class="headerSide header-right green"></div>
						<div class="firstLine firstLine-right rotation3">pacific<br /> avenue</div>
					</div>
					<div class="squareSide" id="32">
						<div class="headerSide header-right green"></div>
						<div class="firstLine firstLine-right rotation3">north<br />carolina<br />avenue</div>
					</div>
					<div class="squareSide" id="33">						
						<div class="firstLine firstLine-right no-color rotation3">community<br />chest</div>
					</div>
					<div class="squareSide" id="34">
						<div class="headerSide header-right green"></div>
						<div class="firstLine firstLine-right rotation3">pennsylvania<br /> avenue</div>
					</div>
					<div class="squareSide" id="35">						
						<div class="firstLine firstLine-right no-color rotation3">short<br /> line</div>
					</div>
					<div class="squareSide" id="36">
						<div class="firstLine firstLine-right no-color rotation3">chance</div>
					</div>
					<div class="squareSide" id="37">						
						<div class="headerSide header-right blue"></div>
						<div class="firstLine firstLine-right rotation3">park<br /> place</div>
					</div>
					<div class="squareSide" id="38">						
						<div class="firstLine firstLine-right no-color rotation3">luxury<br /> tax</div>
					</div>
					<div class="squareSide" id="39">
						<div class="headerSide header-right yellowgreen"></div>
						<div class="firstLine firstLine-right rotation3">michoacan</div>
					</div>
				</div>
			</div>

			<div class="row top">
				<div class="square2" id="10">
					<span class="corner corner4" style="line-height:18px; margin:3.5em 0 0 1.5em"> Hospital: <br>lose a turn. pay 100x your roll</span>
				</div>
				<div class="square1" id="9">
					<div class="header header-bottom red"></div>
					<div class="firstLine firstLine-bottom">columbian <br>red bud</div>
				</div>
				<div class="square1" id="8">
					<div class="header header-bottom blue"></div>
					<div class="firstLine firstLine-bottom">thai<br>stick</div>
				</div>
				<div class="square1" id="7">
					<div class="firstLine firstLine-bottom no-color">downtown<br>pharmacy</div>
				</div>
				<div class="square1" id="6">
					<div class="header header-bottom lightblue"></div>
          <div class="header header-bottom lightolive"></div>
					<div class="firstLine firstLine-bottom">gainesville<br /> green</div>
				</div>
				<div class="square1" id="5">	
          <div class="header header-bottom orange"></div>
					<div class="firstLine firstLine-bottom">wacky<br /> weed</div>
				</div>
				<div class="square1" id="4">
					<div class="firstLine firstLine-bottom no-color">Far <br /> Out!</div>
				</div>
				<div class="square1" id="3">
					<div class="header header-bottom green"></div>
					<div class="firstLine firstLine-bottom">home<br /> grown</div>
				</div>
				<div class="square1" id="2">
					<div class="firstLine firstLine-bottom no-color">Flying<br /> Too High:<br>Lose A<br>Turn</div>
				</div>
				<div class="square1" id="1">
					<div class="header header-bottom brown"></div>
					<div class="firstLine firstLine-bottom">Columbian</div>
				</div>
				<div class="square2" id="40">
					<span class="corner corner3"  style="margin:0 1.5em;"><br>Straight <br> Space <br>Collect<br />$500<br /></span>
				</div>
			</div>

		</div>

	</div>

</template>

<style>
div {
	box-sizing: border-box;
	text-transform: uppercase;
}

.responsive {
    background: #cde6d0;
    width: 80vw;
    height: 80vw;
    margin: 10px auto;
}

.mainSquare {
	height: 100%;
	position:relative;
	left: 14px;
}

.row {
	width: 100%;
	display: flex;
}

.top {
	height: 15.384615385%;
}

.center {
	height: 69.23076923%;
}
.square1 {
	outline: 1px solid black;
	flex-grow: 1;
	position: relative;
}

.square2 {
	flex-grow: 2;
	outline: 1px solid black;
	display: flex;
	flex-direction: column;
	position: relative;
}

.square9 {
	flex-grow: 9;
	outline: 1px solid black;
}

.squareSide {
	outline: 1px solid black;
	width: 100%;
	flex-grow: 1;
	position: relative;
}

.header {
	height: 21%;
	position: absolute;
	outline: 2px solid black;
	background: grey;
	/* width: 100%; */
}

.headerSide {
	/* height: 100%; */
	width: 21%;
	position: absolute;
	outline: 2px solid black;
}

.header-top {
	bottom: 1px;
	left: 1px;
	right: 1px;
}

.header-bottom {
	top: 1px;
	left: 1px;
	right: 1px;
}

.header-left {
	top: 1px;
	bottom: 1px;
	right: 1px;
	background: grey;
}

.header-right {
	top: 1px;
	bottom: 1px;
	left: 1px;
	background: grey;
}

.firstLine {
	position: absolute;
	font-size: 0.7vw;
	font-weight: 500;
	line-height: 1vw;
	text-align: center;
}

.firstLine-top {
	left: 1px;
	right: 1px;
	bottom: 30%;
	height: 10%;
}

.firstLine-top.no-color {
	bottom: 12%;
}

.firstLine-left {
	top: 0px;
	bottom: 0px;
	right: 42%;
}

.firstLine-left.no-color {
	right: 23%;
}

.firstLine-right {
	top: 0;
	bottom: 0;
	left: 42%;
}

.firstLine-right.no-color {
	left: 23%;
}

.firstLine-bottom {
	left: 0;
	right: 0;
	top: 30%;
}

.firstLine-bottom.no-color {
	top: 12%;
}

.red {
  background-color: #ed1b24;
}

.yellow {
  background-color: #fef200;
}

.lightblue {
  background-color: #aae0fa;
}

.brown {
  background-color: #955436;
}

.blue {
  background-color: #0072bb;
}

.green {
  background-color: #1fb25a;
}

.orange {
  background-color: #f7941d;
}

.purple {
  background-color: #d93a96;
}

.rotation1 {
  transform: rotate(90deg);
}

.rotation2 {
  transform: rotate(180deg);
}

.rotation3 {
  transform: rotate(-90deg);
}

.logoBox {
	width: 46%;
	background: #ed1b24;
	position: absolute;
	transform: rotateZ(-45deg) translateX(-27%) translateY(237%);
	border: 3px solid black;
	text-align: center;
	box-shadow: inset 0px 2px 12px 0px white;
}

.logoName {
	font-size: 7.1vw;
	color: white;
	font-family: futura;
	text-shadow: -4px 3px 0px black;
	-webkit-text-fill-color: white; /* Will override color (regardless of order) */
	-webkit-text-stroke-width: 2px;
	-webkit-text-stroke-color: #cfc2c3;
}

.card-box {
	position: absolute;
	width: 15%;
	height: 9vw;
}

.card-blue {
	background: linear-gradient(#4ccaf4, #a3dff9);
	transform: rotateZ(-45deg) translateX(-13%) translateY(66%);
}

.card-blue-inside {
    background: linear-gradient(#a3dff9, #4ccaf4);
    width: 94%;
    height: 94%;
    margin: 0.3vw auto;
    position: relative;
}

.card-orange {
	background: linear-gradient(#f99120, #f57420);
	transform: rotateZ(-45deg) translateX(-13%) translateY(610%);
}

.card-orange-inside {
    background: linear-gradient(#f57420, #f99120);
    width: 94%;
    height: 94%;
    margin: 0.3vw auto;
    position: relative;
}

.corner {
	position: absolute;
	text-align: center;
	line-height: 8vw;
	font-size: 1.2vw;
	font-weight: 500;
}

.corner1 {
    transform: rotateZ(135deg) translateX(-66%) translateY(-15%);
}

.corner2 {
    transform: rotateZ(-135deg) translateX(-30%) translateY(23%);
    line-height: 9vw;
}

.corner3 {
    transform: rotateZ(-45deg) translateX(-14%) translateY(26%);
    line-height: 1.4vw;
    font-size: 1vw;
}

.corner4 {
    transform: rotateZ(45deg) translateX(-9%) translateY(-31%);
    line-height: 7vw;
}

.squareCorner {
	height: 65%;
	width: 65%;
	border: 2px solid black;
	right: -1px;
	top: -1px;
	position: absolute;
}

.corner4-left {
	position: absolute;
	transform: rotateZ(90deg) translateX(80%) translateY(-36%);
	font-size: 1.2vw;
	font-weight: 500;
}

.corner4-bottom {
	position: absolute;
	transform: translateX(112%) translateY(720%);
	font-size: 1.2vw;
	font-weight: 500;
}
</style>

<script>
"use strict"

import players from './players.js'; 
import spaces from './spaces.js';
import bummers from './bummers.js';
import farouts from './farouts.js';
import strains from './strains.js';

Vue.use([
	players,
	spaces,
	bummers,
	farouts,
	strains
	])
export default {
    data() {
		return {
			"skipped": [],
			"activePlayerId": 0,
			"players": players,
			"spaces": spaces,
			"bummers": bummers,
			"farouts": farouts,
			"strains": strains
		}
	},
	methods: {
		sixSidedDie(min,max) {
			min = Math.ceil(min);
			max = Math.floor(max);
			return Math.floor(Math.random() * (max - min + 1)) + min;
		},
		gameRoll() {
			let first = this.sixSidedDie(1,6) 
			let second = this.sixSidedDie(1,6)
			return first + second
		},
		moveCash(amount, player) {
			player.cash = player.cash - amount
			bank = bank + amount
			return player.cash
		},
		completeTurn() {
			this.activePlayerId++
            
			if (this.activePlayerId > 7) {
				this.activePlayerId = 0
			}
			console.log("active player id: " + this.activePlayerId)
			if (this.activePlayerId === this.players.indexOf()) {
				let player = players[activePlayerId]
				if (player.playing !== true) {
					return this.completeTurn()
				}
			}

			if (this.skipped.includes(this.activePlayerId)) {
				this.skipped.splice(this.skipped.indexOf(this.activePlayerId), 1)
				console.log("end of turn, player id: " + this.activePlayerId)
				console.log("skipped player id: " + this.activePlayerId)
				return this.completeTurn()
			}
			console.log("end of turn, player id: " + this.activePlayerId)
			return gameRoll()
		},
		loseTurn() {
			return this.skipped.push(this.skipped[this.activePlayerId])
		}
	}  
}
</script>

// resources/js/components/potluck/board.svelte
<main>
<div class="responsive">
	<div class="mainSquare">
		<div class="row top">
			<div class="square2" id="20"><span class="corner corner1">free <br /> parking</span></div>
			<div class="square1" id="21">
				<div class="header header-top red"></div>
				<div class="firstLine firstLine-top rotation2">kentucky <br /> avenue</div>
			</div>
			<div class="square1" id="22">
				<div class="firstLine firstLine-top no-color rotation2">chance</div>
			</div>
			<div class="square1" id="23">
				<div class="header header-top red"></div>
				<div class="firstLine firstLine-top rotation2">indiana <br /> avenue</div>
			</div>
			<div class="square1" id="24">
				<div class="header header-top red"></div>
				<div class="firstLine firstLine-top rotation2">illinios <br /> avenue</div>
			</div>
			<div class="square1" id="25">
				<div class="firstLine firstLine-top no-color rotation2">b. & o. <br /> railroad</div>
			</div>
			<div class="square1" id="26">
				<div class="header header-top yellow"></div>
				<div class="firstLine firstLine-top rotation2">atlantic <br /> avenue</div>
			</div>
			<div class="square1" id="27">
				<div class="header header-top yellow"></div>
				<div class="firstLine firstLine-top rotation2">ventnor <br /> avenue</div>
			</div>
			<div class="square1" id="28">
				<div class="firstLine firstLine-top no-color rotation2">water <br /> works</div>
			</div>
			<div class="square1" id="29">
				<div class="header header-top yellow"></div>
				<div class="firstLine firstLine-top rotation2">marvin <br /> gardens</div>
			</div>
			<div class="square2" id="30"><span class="corner corner2">go to<br />jail</span></div>
		</div>

		<div class="row center">
			<div class="square2">
				<div class="squareSide" id="19">
					<div class="headerSide header-left orange"></div>
					<div class="firstLine firstLine-left rotation1">new york <br /> avenue</div>
				</div>
				<div class="squareSide" id="18">
					<div class="headerSide header-left orange"></div>
					<div class="firstLine firstLine-left rotation1">tennessee <br /> avenue</div>
				</div>
				<div class="squareSide" id="17">
					<div class="firstLine firstLine-left no-color rotation1">community<br /> chest</div>
				</div>
				<div class="squareSide" id="16">
					<div class="headerSide header-left orange"></div>
					<div class="firstLine firstLine-left rotation1">st.james <br />place</div>
				</div>
				<div class="squareSide" id="15">
					<div class="firstLine firstLine-left no-color rotation1">pennsylvania<br> railroad</div>
				</div>
				<div class="squareSide" id="14">
					<div class="headerSide header-left purple"></div>
					<div class="firstLine firstLine-left rotation1">virginia<br /> avenue</div>
				</div>
				<div class="squareSide" id="13">
					<div class="headerSide header-left purple"></div>
					<div class="firstLine firstLine-left rotation1">states<br /> avenue</div>
				</div>
				<div class="squareSide" id="12">
					<div class="firstLine firstLine-left no-color rotation1">electric<br />company</div>
				</div>
				<div class="squareSide" id="11">
					<div class="headerSide header-left white"></div>
					<div class="firstLine firstLine-left rotation1">columbian<br />chiba</div>
				</div>
			</div>
			<div class="square9">
				<div class="card-box card-blue">
					<div class="card-blue-inside"></div>
				</div>
				<div class="logoBox">
					<span class="logoName">Pot Luck</span>
				</div>
				<div class="card-box card-orange">
					<div class="card-orange-inside"></div>
				</div>
			</div>
			<div class="square2">
				<div class="squareSide" id="31">
					<div class="headerSide header-right green"></div>
					<div class="firstLine firstLine-right rotation3">pacific<br /> avenue</div>
				</div>
				<div class="squareSide" id="32">
					<div class="headerSide header-right green"></div>
					<div class="firstLine firstLine-right rotation3">north<br />carolina<br />avenue</div>
				</div>
				<div class="squareSide" id="33">
					<div class="firstLine firstLine-right no-color rotation3">community<br />chest</div>
				</div>
				<div class="squareSide" id="34">
					<div class="headerSide header-right green"></div>
					<div class="firstLine firstLine-right rotation3">pennsylvania<br /> avenue</div>
				</div>
				<div class="squareSide" id="35">
					<div class="firstLine firstLine-right no-color rotation3">short<br /> line</div>
				</div>
				<div class="squareSide" id="36">
					<div class="firstLine firstLine-right no-color rotation3">chance</div>
				</div>
				<div class="squareSide" id="37">
					<div class="headerSide header-right blue"></div>
					<div class="firstLine firstLine-right rotation3">park<br /> place</div>
				</div>
				<div class="squareSide" id="38">
					<div class="firstLine firstLine-right no-color rotation3">luxury<br /> tax</div>
				</div>
				<div class="squareSide" id="39">
					<div class="headerSide header-right yellowgreen"></div>
					<div class="firstLine firstLine-right rotation3">michoacan</div>
				</div>
			</div>
		</div>

		<div class="row top">
			<div class="square2" id="10">
				<span class="corner corner4" style="line-height:18px; margin:3.5em 0 0 1.5em"> Hospital: <br>lose a
					turn. pay 100x your roll</span>
			</div>
			<div class="square1" id="9">
				<div class="header header-bottom red"></div>
				<div class="firstLine firstLine-bottom">columbian <br>red bud</div>
			</div>
			<div class="square1" id="8">
				<div class="header header-bottom blue"></div>
				<div class="firstLine firstLine-bottom">thai<br>stick</div>
			</div>
			<div class="square1" id="7">
				<div class="firstLine firstLine-bottom no-color">downtown<br>pharmacy</div>
			</div>
			<div class="square1" id="6">
				<div class="header header-bottom lightblue"></div>
				<div class="header header-bottom lightolive"></div>
				<div class="firstLine firstLine-bottom">gainesville<br /> green</div>
			</div>
			<div class="square1" id="5">
				<div class="header header-bottom orange"></div>
				<div class="firstLine firstLine-bottom">wacky<br /> weed</div>
			</div>
			<div class="square1" id="4">
				<div class="firstLine firstLine-bottom no-color">Far <br /> Out!</div>
			</div>
			<div class="square1" id="3">
				<div class="header header-bottom green"></div>
				<div class="firstLine firstLine-bottom">home<br /> grown</div>
			</div>
			<div class="square1" id="2">
				<div class="firstLine firstLine-bottom no-color">Flying<br /> Too High:<br>Lose A<br>Turn</div>
			</div>
			<div class="square1" id="1">
				<div class="header header-bottom brown"></div>
				<div class="firstLine firstLine-bottom">Columbian</div>
			</div>
			<div class="square2" id="40">
				<span class="corner corner3" style="margin:0 1.5em;"><br>Straight <br> Space
					<br>Collect<br />$500<br /></span>
			</div>
		</div>

	</div>

</div>

</main>

<style>
	div {
		box-sizing: border-box;
		text-transform: uppercase;
	}

	.responsive {
		background: #cde6d0;
		width: 80vw;
		height: 80vw;
		margin: 10px auto;
	}

	.mainSquare {
		height: 100%;
		position: relative;
		left: 14px;
	}

	.row {
		width: 100%;
		display: flex;
	}

	.top {
		height: 15.384615385%;
	}

	.center {
		height: 69.23076923%;
	}

	.square1 {
		outline: 1px solid black;
		flex-grow: 1;
		position: relative;
	}

	.square2 {
		flex-grow: 2;
		outline: 1px solid black;
		display: flex;
		flex-direction: column;
		position: relative;
	}

	.square9 {
		flex-grow: 9;
		outline: 1px solid black;
	}

	.squareSide {
		outline: 1px solid black;
		width: 100%;
		flex-grow: 1;
		position: relative;
	}

	.header {
		height: 21%;
		position: absolute;
		outline: 2px solid black;
		background: grey;
		/* width: 100%; */
	}

	.headerSide {
		/* height: 100%; */
		width: 21%;
		position: absolute;
		outline: 2px solid black;
	}

	.header-top {
		bottom: 1px;
		left: 1px;
		right: 1px;
	}

	.header-bottom {
		top: 1px;
		left: 1px;
		right: 1px;
	}

	.header-left {
		top: 1px;
		bottom: 1px;
		right: 1px;
		background: grey;
	}

	.header-right {
		top: 1px;
		bottom: 1px;
		left: 1px;
		background: grey;
	}

	.firstLine {
		position: absolute;
		font-size: 0.7vw;
		font-weight: 500;
		line-height: 1vw;
		text-align: center;
	}

	.firstLine-top {
		left: 1px;
		right: 1px;
		bottom: 30%;
		height: 10%;
	}

	.firstLine-top.no-color {
		bottom: 12%;
	}

	.firstLine-left {
		top: 0px;
		bottom: 0px;
		right: 42%;
	}

	.firstLine-left.no-color {
		right: 23%;
	}

	.firstLine-right {
		top: 0;
		bottom: 0;
		left: 42%;
	}

	.firstLine-right.no-color {
		left: 23%;
	}

	.firstLine-bottom {
		left: 0;
		right: 0;
		top: 30%;
	}

	.firstLine-bottom.no-color {
		top: 12%;
	}

	.red {
		background-color: #ed1b24;
	}

	.yellow {
		background-color: #fef200;
	}

	.lightblue {
		background-color: #aae0fa;
	}

	.brown {
		background-color: #955436;
	}

	.blue {
		background-color: #0072bb;
	}

	.green {
		background-color: #1fb25a;
	}

	.orange {
		background-color: #f7941d;
	}

	.purple {
		background-color: #d93a96;
	}

	.rotation1 {
		transform: rotate(90deg);
	}

	.rotation2 {
		transform: rotate(180deg);
	}

	.rotation3 {
		transform: rotate(-90deg);
	}

	.logoBox {
		width: 46%;
		background: #ed1b24;
		position: absolute;
		transform: rotateZ(-45deg) translateX(-27%) translateY(237%);
		border: 3px solid black;
		text-align: center;
		box-shadow: inset 0px 2px 12px 0px white;
	}

	.logoName {
		font-size: 7.1vw;
		color: white;
		font-family: futura;
		text-shadow: -4px 3px 0px black;
		-webkit-text-fill-color: white;
		/* Will override color (regardless of order) */
		-webkit-text-stroke-width: 2px;
		-webkit-text-stroke-color: #cfc2c3;
	}

	.card-box {
		position: absolute;
		width: 15%;
		height: 9vw;
	}

	.card-blue {
		background: linear-gradient(#4ccaf4, #a3dff9);
		transform: rotateZ(-45deg) translateX(-13%) translateY(66%);
	}

	.card-blue-inside {
		background: linear-gradient(#a3dff9, #4ccaf4);
		width: 94%;
		height: 94%;
		margin: 0.3vw auto;
		position: relative;
	}

	.card-orange {
		background: linear-gradient(#f99120, #f57420);
		transform: rotateZ(-45deg) translateX(-13%) translateY(610%);
	}

	.card-orange-inside {
		background: linear-gradient(#f57420, #f99120);
		width: 94%;
		height: 94%;
		margin: 0.3vw auto;
		position: relative;
	}

	.corner {
		position: absolute;
		text-align: center;
		line-height: 8vw;
		font-size: 1.2vw;
		font-weight: 500;
	}

	.corner1 {
		transform: rotateZ(135deg) translateX(-66%) translateY(-15%);
	}

	.corner2 {
		transform: rotateZ(-135deg) translateX(-30%) translateY(23%);
		line-height: 9vw;
	}

	.corner3 {
		transform: rotateZ(-45deg) translateX(-14%) translateY(26%);
		line-height: 1.4vw;
		font-size: 1vw;
	}

	.corner4 {
		transform: rotateZ(45deg) translateX(-9%) translateY(-31%);
		line-height: 7vw;
	}

	.squareCorner {
		height: 65%;
		width: 65%;
		border: 2px solid black;
		right: -1px;
		top: -1px;
		position: absolute;
	}

	.corner4-left {
		position: absolute;
		transform: rotateZ(90deg) translateX(80%) translateY(-36%);
		font-size: 1.2vw;
		font-weight: 500;
	}

	.corner4-bottom {
		position: absolute;
		transform: translateX(112%) translateY(720%);
		font-size: 1.2vw;
		font-weight: 500;
	}
</style>

<script>
import { onMount } from "svelte";

onMount(() => {
	console.log("the board has mounted");
});

import players from './players.js';
import spaces from './spaces.js';
import bummers from './bummers.js';
import farouts from './farouts.js';
// import strains from  './strains.js';

let data = [
	players,
	spaces,
	bummers,
	farouts,
	// strains 
]

let state = {
	data: data,
	skipped: [],
	activePlayerId: 0
}

function sixSidedDie (min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min + 1)) + min;
}

function gameRoll() {
	let first = this.sixSidedDie(1, 6)
	let second = this.sixSidedDie(1, 6)
	return first + second
}

function moveCash(amount, player) {
	player.cash = player.cash - amount
	bank = bank + amount
	return player.cash
}

function completeTurn() {
	this.activePlayerId++

	if (this.activePlayerId > 7) {
		this.activePlayerId = 0
	}
	console.log("active player id: " + this.activePlayerId)
	if (this.activePlayerId === this.players.indexOf()) {
		let player = players[activePlayerId]
		if (player.playing !== true) {
			return this.completeTurn()
		}
	}

	if (this.skipped.includes(this.activePlayerId)) {
		this.skipped.splice(this.skipped.indexOf(this.activePlayerId), 1)
		console.log("end of turn, player id: " + this.activePlayerId)
		console.log("skipped player id: " + this.activePlayerId)
		return this.completeTurn()
	}
	console.log("end of turn, player id: " + this.activePlayerId)
	return gameRoll()
}

function loseTurn() {
	return this.skipped.push(this.skipped[this.activePlayerId])
}

</script>
